appname = agroempleo_registro_de_empleo
httpport = 8083
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1/agrito?sslmode=disable&search_path=registro_de_empleo
